SELECT CONCAT( a.ID_AUTOR,' - ' , a.NOME_AUTOR) AS AUTOR, CONCAT(l.ID_LIVRO, ' - ' , l.TITULO) AS LIVRO, CONCAT(s.ID_SITUACAO, ' - ' , s.NOME_SITUACAO) AS SITUACAO
FROM AUTOR a
INNER JOIN ESCRITA e ON a.ID_AUTOR = e.ID_AUTOR
INNER JOIN LIVRO l ON e.ID_LIVRO = l.ID_LIVRO
INNER JOIN SITUACAO s ON l.ID_SITUACAO = s.ID_SITUACAO
ORDER BY l.ID_LIVRO; 

SELECT a.NOME_AUTOR, IFNULL(l.TITULO, 'Nenhum livro associado') AS TITULO_DO_LIVRO
FROM AUTOR a
LEFT OUTER JOIN ESCRITA e ON a.ID_AUTOR = e.ID_AUTOR
LEFT OUTER JOIN LIVRO l ON e.ID_LIVRO = l.ID_LIVRO;

SELECT a.ID_AUTOR, a.NOME_AUTOR,
(SELECT COUNT(*) FROM ESCRITA e WHERE e.ID_AUTOR = a.ID_AUTOR) AS NUMERO_DE_LIVROS_ESCRITOS
FROM AUTOR a;

SELECT TITULO, DATA_PUBLICACAO
FROM LIVRO
WHERE DATA_PUBLICACAO = (SELECT MIN(DATA_PUBLICACAO) FROM LIVRO);

SELECT a.ID_AUTOR, a.NOME_AUTOR, COUNT(e.ID_LIVRO) AS TOTAL_DE_LIVROS_ESCRITOS
FROM AUTOR a
INNER JOIN ESCRITA e ON a.ID_AUTOR = e.ID_AUTOR
GROUP BY a.ID_AUTOR, a.NOME_AUTOR
HAVING COUNT(e.ID_LIVRO) >= 3;

SELECT NOME_AUTOR FROM AUTOR
UNION
SELECT TITULO FROM LIVRO;
